name: assessment_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  font_awesome_flutter: ^9.2.0
  firebase_auth: ^3.3.6
  geolocator: ^8.0.5
  google_maps_flutter: ^2.1.1
  firebase_core: ^1.12.0
  shared_preferences: ^2.0.12
  google_sign_in: ^5.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
